craigslist/config/routes.rb
Craigslist::Application.routes.draw do
  root :to => "categories#index"

  resources :categories do
    resources :posts
  end

end

craigslist/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :category_id
  belongs_to :category
end

craigslist/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index # show all categories
    @categories = Category.all
  end

  def show # show category dashboard
    @category = Category.find(params[:id])
  end

  def new # create category
    @category = Category.new
  end

  def create # post to create category
    @category = Category.new(params[:category])
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy # delete category
    category = Category.find(params[:id])
    category.destroy
    redirect_to root_path
  end
end

craigslist/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @category = @post.category
  end

  def new
    @category = Category.find(params[:category_id])
    @post = @category.posts.build
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.build(params[:post])
    if @post.save
      redirect_to category_post_path(@category, @post)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    if @post.save
      redirect_to category_post_path(@category, @post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    category = post.category
    post.destroy
    redirect_to category_path(category)
  end
end

craigslist/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<ul>
  <%= form_for @category do |f| %>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  <% end %>
</ul>

craigslist/app/views/categories/index.html.erb
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

craigslist/app/views/categories/new.html.erb
<h1>Create Category</h1>
<ul>
  <%= form_for @category do |f| %>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  <% end %>
</ul>

craigslist/app/views/categories/show.html.erb
<ul>
  <% @category.posts.each do |post| %>
    <li>
      <%= post.title %>
      <%= post.content %>
    </li>
  <% end %>
    <%= link_to "Create Post", new_category_post_path(@category) %>
   <%= link_to "delete category", category_path(@category), :method => :delete %>

</ul>

craigslist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

craigslist/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<ul>
  <%= form_for [@category, @post] do |f| %>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  <% end %>
</ul>

craigslist/app/views/posts/new.html.erb
<h1>Create Post</h1>
<ul>
  <%= form_for [@category, @post]  do |f| %>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  <% end %>
</ul>

craigslist/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.content %></p>
<%= link_to "edit", edit_category_post_path(@category, @post) %>
<%= link_to "delete", category_post_path(@category, @post), :method => :delete %>