craigslist_jr/config/routes.rb
CraigslistJr::Application.routes.draw do


  root to: "categories#index"

  resources :categories do
    resources :posts
  end

  resources :posts, only: [] do
    resources :replies, only: [:new]
  end

  get '/categories/:category_id/posts/:id/:secret_url', to: 'posts#edit'
end

craigslist_jr/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true
  has_many :posts
end

craigslist_jr/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :price
  has_many :replies
  belongs_to :category
  before_create :generate_secret_url
  validates :title, :body, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}

  def generate_secret_url
    secret = ( (0..9).to_a + ('a'..'z').to_a ).sample(5).join
    while Post.find_by_secret_url(secret)
      secret = ( (0..9).to_a + ('a'..'z').to_a ).sample(5).join
    end
    self.secret_url = secret
  end

end

craigslist_jr/app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :name, :email, :text
  validates :name, :email, :text, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  belongs_to :post
end

craigslist_jr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order('name asc')
  end

  def show
    @category = Category.includes(:posts).find(params[:id])
    @posts = @category.posts.order('created_at desc')
  end
end

craigslist_jr/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @post = @category.posts.build
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.build(params[:post])
    if @category.save
      flash[:notice] = "localhost:3000/categories/#{@category.id}/posts/#{@post.id}/#{@post.secret_url}"
      redirect_to @category
    else
      p @category.errors.full_messages
      redirect_to new_category_post_path(@category)
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    if params[:secret_url] != @post.secret_url
      redirect_to '/404.html'
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @category
    else
      redirect_to edit_category_post_path(@category, @post)
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to @category
  end
end

craigslist_jr/app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @reply = @post.replies.build
  end
end

craigslist_jr/app/views/posts/edit.html.erb
<h1>Edit post from <%= @category.name.titleize %></h1>
<%= form_for [@category, @post]  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.label :price %>
  <%= f.text_field :price %><br>
  <%= f.submit  %>
<% end %>

<%= link_to('delete', category_post_path(@category, @post), method: :delete, confirm: 'really delete?') %>

craigslist_jr/app/views/posts/new.html.erb
<h1>Create a new post in <%= @category.name.titleize %></h1>
<%= form_for [@category, @post]  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.label :price %>
  <%= f.text_field :price %><br>
  <%= f.submit  %>
<% end %>

craigslist_jr/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<p><%= @post.price %></p>